"""Create accounts modify transactions tables

Revision ID: e0c6790756dc
Revises: b30ee19e254f
Create Date: 2024-07-17 21:56:15.004081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c6790756dc'
down_revision = 'b30ee19e254f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        
        batch_op.create_foreign_key('fk_transactions_treasurer_id', 'users', ['treasurer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_transactions_account_id', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_transactions_owner_id', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('account')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('fk_transactions_owner_id', type_='foreignkey')
        batch_op.drop_constraint('fk_transactions_account_id', type_='foreignkey')
        batch_op.drop_constraint('fk_transactions_treasurer_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['treasurer_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])
        batch_op.drop_column('account_id')

    op.drop_table('accounts')
    # ### end Alembic commands ###
